### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by phougt** [artsyfriedchicken/EdgyArc-fr#13]
**Describe the bug**
When I tried out the beta7 and beta7.1, my Firefox Dev Edition just broke. I couldn't move the browser windows or interact with any button on the toolbar.

**To Reproduce**
1. Copy-Paste the contents into the chrome folder

**Expected behavior**
I expected everything to be working normally, clickable.

**Desktop (please complete the following information):**
 - OS: Windows 11 pro edition
 - Browser: Firefox Dev Edition
 - Version: 125.0b3 (64-bit)
 - 

**Additional context**
Everything froze except the content of the websites itself.

**Comment by artsyfriedchicken** [comment]
was this behaviour present in the beta 6 release?

**Comment by phougt** [comment]
Hello dear, 
no, it doesn't present in the beta 6 release.

**Comment by artsyfriedchicken** [comment]
Righto, ill figure out a fix asap!

**Comment by phougt** [comment]
Hello dear,
I tried it again. The toolbar buttons work fine, but the browser window is bit unresponsive. I couldn't make it snap, sharp corner, big white line around the border.
Here are some screenshot:
![NVIDIA_Share_q9TsIIZzCn](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/74492753/4afb302f-9c9b-4f97-bd7d-e41e9860c2ea)
![firefox_Zq0kV4IkJR](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/74492753/86cf3ef5-915f-4314-b28b-235dfd3f8264)

**Comment by artsyfriedchicken** [comment]
That is VERY weird. do you have any other mods applied to userchrome.css?

**Comment by phougt** [comment]
I did not applied anything. I will try to re-paste the contents in chrome folder again.

**Comment by phougt** [comment]
Thank you for your hard work. I really appreciate your help.

**Comment by phougt** [comment]
I will try it on the ff 124, and see if the problem still persist.

**Comment by phougt** [comment]
Unfortunately, the problem still present. I think the problem is my machine or user error.
Thank you again for your help.

**Comment by artsyfriedchicken** [comment]
This bug is so fucking odd and out of nowhere its its an earworm for me lmao! 

I'm deffo gonna keep an eye out for the bug and see if i can replicate it! 

In the meantime, if you have some free time on your hands and feel so inclined, id love it if you could try selecting the white border using the element picker in browser toolbox and sending me a screenshot or details of which element is causing the border!! 
So far, the only thing ive added a white border to is #main-window::before, but i can see the #main-window::before border being drawn INSIDE the fat white border in your screenshot as well.

**Comment by TickyTacky999** [comment]
I had the exact same issue as you, I've tried it on ff 124 and the latest beta build

**Comment by artsyfriedchicken** [comment]
Can either one of you please open the browser toolbox in firefox, use the element inspector to select the white border and tell me what element it is? I can't seem to replicate the bug on my vm

**Comment by TickyTacky999** [comment]
> Can either one of you please open the browser toolbox in firefox, use the element inspector to select the white border and tell me what element it is? I can't seem to replicate the bug on my vm 

Sure thing! I am not at home yet due to work. When I get home I will do it!

**Comment by TickyTacky999** [comment]
I am pretty dumb when it comes to all this stuff. However, I tried doing what you asked. But it doesn't seem like I can inspect that border at all. (Or I might be doing something wrong).

I used the element inspector, hovered over it but nothing shows up.
If I did something wrong feel free to explain the correct steps so I can do it for you..

I did manage to replicate it tho.

![firefox_tpRiH75TAO](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/158566440/30285f79-68cd-400f-b06a-aeec88337db6)

![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/158566440/8a4d9c26-47a8-4346-a0a4-d7f44f9fb75d)

**Comment by artsyfriedchicken** [comment]
> I am pretty dumb when it comes to all this stuff. However, I tried doing what you asked. But it doesn't seem like I can inspect that border at all. (Or I might be doing something wrong).
> 
> I used the element inspector, hovered over it but nothing shows up. If I did something wrong feel free to explain the correct steps so I can do it for you..
> 
> I did manage to replicate it tho.
> 
> ![firefox_tpRiH75TAO](https://private-user-images.githubusercontent.com/158566440/317249578-30285f79-68cd-400f-b06a-aeec88337db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDcwNzYsIm5iZiI6MTcxMTU0Njc3NiwicGF0aCI6Ii8xNTg1NjY0NDAvMzE3MjQ5NTc4LTMwMjg1Zjc5LTY4Y2QtNDAwZi1iMDZhLWFlZWM4ODMzN2RiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzM5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDEwNzZmOTZlODQwNDQ5Y2NmYjI0M2QxNjlmZGMyZGRhNTM5YTI4NDc0ZTM2ZTRiNjViM2ViMzI2OGYwNTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W-3RZxISj-UevXQcL0d3ZD87opnb6JldE5ayXd36ysI)
> 
> ![image](https://private-user-images.githubusercontent.com/158566440/317249673-8a4d9c26-47a8-4346-a0a4-d7f44f9fb75d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDcwNzYsIm5iZiI6MTcxMTU0Njc3NiwicGF0aCI6Ii8xNTg1NjY0NDAvMzE3MjQ5NjczLThhNGQ5YzI2LTQ3YTgtNDM0Ni1hMGE0LWQ3ZjQ0ZjlmYjc1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzM5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2NjZTZiODQ1Y2JlM2Y1ZjMwN2MyODUxYWRjZTM3MTljNzhiZTBlNWI2NWFiM2VlNTc5YTdkZmI1MTU2NWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IQyaCnwiK6RIoVbwQO1M4CTKnPWnLlUvuTcrNo1vk24)

Oh that is BEYOND bizzare lmao 

can you pull my latest changes and try it on a fresh new profile please? 

![Screen Shot 2024-03-27 at 7 42 01 PM](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/f321f13f-0bac-4a26-bd7a-5bc46db9cf44)
This is how it looks for me on windows atm. And im pretty fucking stumped lmao

**Comment by TickyTacky999** [comment]
I used Revo Uninstaller to wipe Firefox and all it's data, reinstalled it.
Then I pulled the new changes you made, set it up and voila! Looks like it's fixed!

![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/158566440/1a57b0ca-5e1c-413d-9944-f5ddc6c7a3df)

**Comment by phougt** [comment]
Wow, I will try that as well.

**Comment by TickyTacky999** [comment]
The only thingy I have is: 
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/158566440/801f19f9-b914-4006-86e9-7d5303d018e4)
Is this normal?

**Comment by artsyfriedchicken** [comment]
> The only thingy I have is: ![image](https://private-user-images.githubusercontent.com/158566440/317297546-801f19f9-b914-4006-86e9-7d5303d018e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDg1MzUsIm5iZiI6MTcxMTU0ODIzNSwicGF0aCI6Ii8xNTg1NjY0NDAvMzE3Mjk3NTQ2LTgwMWYxOWY5LWI5MTQtNDAwNi04NmU5LTdkNTMwM2QwMThlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxNDAzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjEwMmQ4YmJhYzE4NWJiNzllNTY4MTZmOTlhMGZjMGMxNGI5NWE5MzFhMGIwNDI0N2M5OGU0NTNhZTU3YzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0i2FCQqxC-eo3Fpz0fk9BLYxJC-SuBtShc1M1X9EmLk) Is this normal?

no it is not. but its a known bug. My eyes hurt rn, im gonna take a crack at it in a few hours. 

PS - please do let me know if you face the "window randomly shrinks to 1px speck on the screen" bug - it is *most definitely* a bug, and not your browser being hacked. XD 

also, PLEASE make sure you have uc.tweak.af.not-translucent enabled!!! windows REALLY doesnt seem to like it when i declare firefox to have a transparent bg on :root

**Comment by phougt** [comment]
I just tried version 8. It works flawlessly. Thank you for your hard work. 
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/74492753/32353f72-53aa-4d42-b8d8-3920d02859b4)

**Comment by artsyfriedchicken** [comment]
BTW, GUYS, try sticking the reload button on the RIGHT of the addressbar, i added some css to make it sit inside the urlbar when you do that!

**Comment by phougt** [comment]
> i added some css to make it sit inside the urlbar when you do that!

![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/74492753/7f601f70-ea4e-451a-bb13-b85d5a1b3f9e)

Nice

**Comment by artsyfriedchicken** [comment]
> btw, do you mind sharing with us about how you fix the buggy window with thick white border?

I would if i fucking could LMAO 

i just faffed around with the code a bit and it fixed itself man. literally couldnt replicate the bug on my end. at all. even once. XD

**Comment by artsyfriedchicken** [comment]
The only changes that i made were 
- fixed the padding and margins on the titlebar buttons, 
- made sure #main-window::before doesnt apply to windows
- made sure #main-window doesnt have a transparent background (this kept making my firefox window randomly shrink and disappear into a single pixel)
