### ISSUE TITLE
Firefox window is not transparent

### ISSUE THREAD

**Issue by arcxne** [artsyfriedchicken/EdgyArc-fr#20]
**Describe the bug**
The firefox window (sidebar, toolbar, etc) is not transparent.

**To Reproduce**
Follow install instructions on Readme. Did not set `uc.tweak.af.not-translucent` to `true`.

**Expected behavior**
Expected firefox window to be translucent, like screenshots.

**Screenshots**
<img width="1912" alt="image" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/103825628/8346f5f9-3518-42fc-9e76-1917b4c760d1">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 125.0b5

**Comment by artsyfriedchicken** [comment]
Please make sure `layout.css.color-mix.enabled` is enabled

**Comment by artsyfriedchicken** [comment]
PLease make sure you have all of these set to true 

toolkit.legacyUserProfileCustomizations.stylesheets
svg.context-properties.content.enabled
layout.css.color-mix.enabled
layout.css.light-dark.enabled
layout.css.has-selector.enabled

I just downloaded 125 b5 and transparencies work.

**Comment by artsyfriedchicken** [comment]
That is very odd indeed!
  
![Screen Shot 2024-03-29 at 4 58 15 PM](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/2778db6e-eef3-4ec2-b264-b7c3d2f0160f)
I cant get it to replicate the bug :(

**Comment by arcxne** [comment]
I've been trying multiple translucent themes on Github and none of them seem to work, so it is most likely an issue on my end :/ In the meantime, I'll just stick to non-translucent, no biggie.

Sorry for the trouble!

P.S. I've been looking for a theme like this forever because I too loved Arc but prefer FOSS. Thank you so much and wish you the best!

**Comment by artsyfriedchicken** [comment]
woooo! Do let me know if a full ff reinstall works! 

PS - older macos blur themes dont work anymore because ff stopped supporting the old way of enabling blur. RN what im doing is making FF treat the browser window as a menu popup XD

**Comment by artsyfriedchicken** [comment]
Do you happen to have reduce transparency turned on in macos settings?? that might be one reason...

**Comment by arcxne** [comment]
I cannot believe how unbelievable stupid I unbelievably am. Yes, reduce transparency was the culprit 🤦‍♂️
So sorry for the trouble!
