### ISSUE TITLE
Sidebar does not collapse

### ISSUE THREAD

**Issue by MalcolmMielle** [artsyfriedchicken/EdgyArc-fr#23]
**Describe the bug**
die bar does not collapse

**To Reproduce**
Install the chrome folder, sideberry settings, and restart firefox

**Expected behavior**
The sidebar collapses

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox

**Comment by artsyfriedchicken** [comment]
Please make sure you have [userchrome toggle](https://addons.mozilla.org/en-US/firefox/addon/userchrome-toggle/) installed anduse the userchrome toggle toolbar button.
