### ISSUE TITLE
Sidebar always collapsed is not always

### ISSUE THREAD

**Issue by AkiVonAkira** [artsyfriedchicken/EdgyArc-fr#25]
**Describe the bug**
`uc.tweak.af.sidebar-always-collapsed` doesn't work when opening a new tab

**Expected behavior**
`uc.tweak.af.sidebar-always-collapsed` should keep the sidebar always collapsed
I attached a video too where you can see it getting uncollapsed once I open a new tab.
I'm on latest version with no code changes unlike last time where I had to remove some title prefaces to disable it from docking

 - OS: Windows 11
 - Browser: Firefox
 - Version: 124.0.1

https://github.com/artsyfriedchicken/EdgyArc-fr/assets/113895247/5d4a70e7-54a0-48b0-a63d-1671a42113eb
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/113895247/1ab68333-8952-42e9-892c-0a218d38986c)

**Comment by artsyfriedchicken** [comment]
This is REALLY weird. I cant seem to replicate this bug :/
