### ISSUE TITLE
Unable to access Firefox Sync and Accounts page in settings

### ISSUE THREAD

**Issue by istoleabread** [artsyfriedchicken/EdgyArc-fr#26]
I'm using latest version of EdgyArc and Firefox v124.0.1
Opening the page about:preferences#sync opens the main settings page, there is no option like firefox account.

![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/68466445/fcadbdba-0ad1-47ec-8a5f-ab4665d3c913)

I'm on Ubuntu 22.04.4 LTS

**Comment by artsyfriedchicken** [comment]
Have you tried reinstalling FF from scratch? Do you have any modifications added to usercontent.css? I cannot seem to replicate this on macos or my win11 and kubuntu VMs...

**Comment by istoleabread** [comment]
Hey, so actually my organization disabled firefox account's sync overnight, so thats why I was unable to access the page. I reinstalled ff and the user logo was gone as well. Nvm, not an edyarc issue, sorry about that
