### ISSUE TITLE
Sidebar does not stay collapsed on hover

### ISSUE THREAD

**Issue by ivnvxd** [artsyfriedchicken/EdgyArc-fr#27]
Even if `uc.tweak.af.sidebar-always-collapsed` is set to `true`, the sidebar is expanding on hover.
By "collapsed" I mean tabs in one line, just icons, no titles.

<img width="763" alt="Screenshot 2024-04-07 at 19 00 11" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97749666/f0b11a4f-33c8-4b7e-8d17-64b7f6663f53">

Release: v1.0.0-beta.9
OS: MacOs Sonoma 14.0 (23A344)
Browser 1: Firefox 124.0.2
Browser 2: Firefox Developer Edition 125.0b9

**Comment by AkiVonAkira** [comment]
So I opened the same issue and decided to dig through the code, I don't think this is implemented just yet... but it was in the readme so we got jebaited ig

**Comment by ivnvxd** [comment]
Yes, I ran through the code too, and didn't find the use of this option there.

Well, in general, I would not be bothered by the lack of this option if the sidebar opens from [this](https://github.com/artsyfriedchicken/EdgyArc-fr/raw/main/screenshots/03.png) to [this](https://github.com/artsyfriedchicken/EdgyArc-fr/raw/main/screenshots/04.png). But in my case it opens to [this](https://github.com/artsyfriedchicken/EdgyArc-fr/raw/main/screenshots/06.png) and all the tabs kind of jump because of that, which looks not nice.

**Comment by moonlinx** [comment]
@ivnvxd - I totally feel you on that, but I was able to find a work around for the time being. If you follow these then you can get rid of that little space for now.

1. Go to sidebery settings > Navigation Bar > Enabled elements
2. There is a section labled "available elements". Choose the Delimiter 
3. Move the delimiter between your tab group space and the hidden panels option
4. voila no matter how much you move it the arrow stays at the bottom

If you need more help, let me know :). Hope this helps!

**Comment by ivnvxd** [comment]
Thank you! But that's not what I meant. This is what the sidebar looks like when it's collapsed: 
<img width="304" alt="Screenshot 2024-04-08 at 23 31 48" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97749666/1b79e57b-aa69-4d09-ae8e-c1d13a4437fa">

And this is how it looks expanded: 
<img width="304" alt="Screenshot 2024-04-08 at 23 31 45" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97749666/9bd69bfe-1e70-44c2-a17a-3f410b0a1bb7">

The only difference between these screenshots is that I hovered my mouse over the sidebar without clicking anything. You can see that the tabs are in different places and the look of the sidebar itself is different. When expanded, it looks as if it is a separate element, rather than one with the borders of the browser window.

**Comment by artsyfriedchicken** [comment]
> The only difference between these screenshots is that I hovered my mouse over the sidebar without clicking anything. You can see that the tabs are in different places and the look of the sidebar itself is different. When expanded, it looks as if it is a separate element, rather than one with the borders of the browser window.

That is because it IS a wholly separate thing my dude... It always has been...

**Comment by artsyfriedchicken** [comment]
> Even if uc.tweak.af.sidebar-always-collapsed is set to true, the sidebar is expanding on hover.
By "collapsed" I mean tabs in one line, just icons, no titles.

cannot replicate. 

https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/49ff7c66-8fb9-4e24-ad96-827a7d7af39c

**Comment by ivnvxd** [comment]
> cannot replicate.
`-moz-bool-pref: uc.tweak.af.sidebar-always-collapsed` is not in the code: https://github.com/search?q=repo%3Aartsyfriedchicken%2FEdgyArc-fr+-moz-bool-pref%3A+uc.tweak.af.sidebar-always-collapsed&type=code 

> That is because it IS a wholly separate thing my dude... It always has been...
Even your video shows that the tab icons move a few pixels when you hover. Why not just leave them where they are?

**Comment by thyttan** [comment]
The `sidebar-always-collapsed` setting also doesn't have an effect for me. Firefox 125.02, Fedora Linux 40.

**Comment by artsyfriedchicken** [comment]
@thyttan @ivnvxd I am really unclear why it isnt working for you. Here is a video of me manually enabling and using it...


https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/038d4fd8-bc8c-446c-b9da-56c810fe9323

also, just for anyone confused in the future, here is where this feature is implemented in the current rewrite -
https://github.com/artsyfriedchicken/EdgyArc-fr/blob/a09d12bf8f11aa6babccd8d6c5907e97c8ee559f/chrome/EdgyArc-fr/autohide-sidebar-modified.css#L10

**Comment by thyttan** [comment]
Thanks! On the latest commit, 9191c408743266040f82609256bbe03d3a6d00e8,  and using `af.edgyarc.sidebar-always-collapsed` instead of `uc.tweak.af.sidebar-always-collapsed` the sidebar stays collapsed.
