### ISSUE TITLE
Translucency no longer works on Mac after version 127.0a1

### ISSUE THREAD

**Issue by dorkbuttt** [artsyfriedchicken/EdgyArc-fr#30]
**Describe the bug**
Translucency on MacOS version 14.5 Beta no longer works in Firefox when switching to its Nightly branch.

**To Reproduce**
1. Follow steps as outlined in installing the theme
2. See error

**Expected behavior**

**Screenshots**
<img width="1356" alt="Screenshot 2024-04-17 at 1 47 25 PM" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/105171762/a8312525-ee5b-4873-bec7-6d76baada850">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 127.0a1

**Additional context**
I made a whole new profile to try to test its reproducibility on the latest nightly version.

**Comment by rustermi** [comment]
mine is broken a bit differently but also transparent where it shouldn't be sind 126:
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97174955/9ca94bb4-38d7-4a3d-9262-8516e205e5ec)

**Comment by rustermi** [comment]
fixed in https://github.com/bmFtZQ/edge-frfox/releases/tag/v24.4.18

**Comment by artsyfriedchicken** [comment]
Le sigh, they patched the workaround i was using. o well. NO MORE BLUR.

**Comment by artsyfriedchicken** [comment]
Found a fix! rewriting parts of the css to make it work :) should be uploaded some point soon!

**Comment by artsyfriedchicken** [comment]
Progress! 
![Screen Shot 2024-04-30 at 10 30 22 AM](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/7b650e8b-c625-494c-bad5-6d6e460a3d2f)
