### ISSUE TITLE
Always collapsed sidebar works only for first opened window

### ISSUE THREAD

**Issue by thyttan** [artsyfriedchicken/EdgyArc-fr#33]
### !!! This may be expected incompatibility between latest changes for Firefox 126 and me running Firefox 125.02.

**Describe the bug**
`af.edgyarc.sidebar-always-collapsed` == `true` only has effect on the first opened instance of Firefox.

**To Reproduce**
1. Open a first instance of Firefox.
2. Notice the sidebar collapses and stays collapsed on mouse hover.
3. Press Ctrl+n to open a new window.
4. See that the sidebar in the new window is not collapsed (BUG).
5. Toggle the userchrome off and then on again.
6. See that the sidebar now collapses in both windows.

**Expected behavior**
If `af.edgyarc.sidebar-always-collapsed` is `true` all new windows should adhere to the setting.

**Screenshots**
First window:
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/1e284ea9-aae6-4387-942b-e489b00306d3)
Second widow directly after Ctrl+n:
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/52219b55-d4ea-4d7d-983c-cde4c3d202c2)
Second window after toggle userchrom off and on again:
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/75b23515-3daa-4d00-8b0a-104758fc264b)
about:config:
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/6a31dadb-2deb-47c9-87a5-d1dd929e7381)
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/a8471cef-71ea-41e9-95ec-b1da7788511e)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Browser: Firefox 125.02
 - Version: commit 9191c408743266040f82609256bbe03d3a6d00e8

**Additional context**

**Comment by artsyfriedchicken** [comment]
Unfortunately, thats a limitation of how userchrome toggle works, and theres really not much i can do regarding it

**Comment by thyttan** [comment]
OK, thanks!

**Comment by luutuankiet** [comment]
@thyttan if this helps, this css toggle addon variant apparently auto reload on new window to address the issue : 
https://addons.mozilla.org/ru/firefox/addon/userchrome-toggle-extended/
