### ISSUE TITLE
Most of context menu not visible when using sidebar-always-collapsed

### ISSUE THREAD

**Issue by thyttan** [artsyfriedchicken/EdgyArc-fr#34]
### !!! This may be expected incompatibility between latest changes for Firefox 126 and me running Firefox 125.02.

**Describe the bug**
With `af.edgyarc.sidebar-always-collapsed` == `true` the menu when right-click / two-finger-click on a tab-icon, most of the menu is hidden and inaccessible.

**To Reproduce**
1. click a tab with two fingers on the touch pad (I suspect this works with a right-click with a mouse as well).
2. See that most of the menu is not visible.

**Expected behavior**
I expect the menu to draw outside of the sidebar, over the web page, so that all of it is visible to the user.

**Workaround**
In Sidebery settings toggle on "Use native context menu".

**Screenshots**
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/0de82506-dcba-4490-bd0f-f36f9ba9daba)
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/97237430/d7e8801e-6b39-4a06-8513-5eafb579a356)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Browser: Firefox 125.02
 - Version: commit 9191c408743266040f82609256bbe03d3a6d00e8

**Additional context**

**Comment by artsyfriedchicken** [comment]
> Expected behavior
> I expect the menu to draw outside of the sidebar, over the web page, so that all of it is visible to the user.

unfortunately that is *not* the expected behaviour as sidebery cannot draw anything outside of the sidebar. The only workaround for this is to use native context menus.

**Comment by thyttan** [comment]
OK - thanks!
