### ISSUE TITLE
URL popout pane transparent

### ISSUE THREAD

**Issue by kaushithamsilva** [artsyfriedchicken/EdgyArc-fr#37]
After the latest update 126.0, the url popout (the box with suggestions and other URLs when the address bar is clicked on) is transparent.

**Comment by Dylvn** [comment]
Hi,

With the update of firefox I have the same problem, not only the suggestion but all around the window

**Comment by artsyfriedchicken** [comment]
> After the latest update 126.0, the url popout (the box with suggestions and other URLs when the address bar is clicked on) is transparent.

Could you please let me know what OS you are running? 
Using macos and win11, i cannot replicate the bug. 

Have you updated to the latest version of edgyarc? do you have the proper flags set in about:config?

**Comment by aniketnegi** [comment]
@kaushithamsilva I had the same problem. Solved it by removing the edgy-arc installation that was previously a dependency.

**Comment by kaushithamsilva** [comment]
I'm on windows 10, solved it by removthe edgy-arc installation,
