### ISSUE TITLE
auto hide side panel

### ISSUE THREAD

**Issue by kittenvr** [artsyfriedchicken/EdgyArc-fr#40]
how do i enable auto hide side panel tabs

**Comment by artsyfriedchicken** [comment]
- Make sure you have [Userchrome Toggle](https://addons.mozilla.org/firefox/addon/userchrome-toggle/) installed and pinned on the nav bar
- enable `af.edgyarc.autohide-sidebar` 
- toggle between expanded and autohide mode using the userchrome toggle button on the nav bar
