### ISSUE TITLE
Sidebery nav bar won't go to bottom

### ISSUE THREAD

**Issue by TaivasJumala** [artsyfriedchicken/EdgyArc-fr#41]
**Describe the bug**
Sidebery nav bar dont't go to bottom

**To Reproduce**
Enable Sidebery Theme
`af.sidebery.edgyarc-theme` to true

**Screenshots**
![图片](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/72904966/3a78da95-c459-4b09-9d3e-1d61dac720c7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser LibreWolf
 - Version 126.1

**Additional context**
I see once toggle the option, it goes to bottom to make sure the animation when sidebar transformed between collapsed and not collapsed has a better alignment.

**Comment by TaivasJumala** [comment]
Besides, addon `privacy badger` lost its icon
![图片](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/72904966/d81d60cc-c793-4d4c-a268-b2f236479043)

**Comment by TaivasJumala** [comment]
I create a clean profile in `about:profile` and test again, it works. So the code should be working.

I then turn off all my browser extensions in my daily profile except sidebery. It still has the same problem. And I tried to reinstall sidebery, clean sidebery style editor, recreate `chrome` folder, none of them work.

Summary:
Your code works fine in LibreWolf, as it has been tested in a clean profile.
Browser extensions may not be related, as I closed other extensions.
Sidebery style editor is empty now, and I tried to reinstall Sidebery, including reset all settings.
No extra code in chrome folder, I recreated it, clone the repo and copied the folder to the right place.

**Comment by artsyfriedchicken** [comment]
Please make sure you dont have af.sidebery.nav-on-top enabled, and you dont have uc.tweak.theme.sidebery enabled?

**Comment by TaivasJumala** [comment]
`af.sidebery.nav-on-top` = true

Now I know why, thank you. Sorry, I can barely notice that, I asked a stupid question.
`uc.tweak.theme.sidebery` is not enabled.
I think you have done a great job like [KiKaraage/ArcWTF](https://github.com/KiKaraage/ArcWTF), and it's worth more noticing.
