### ISSUE TITLE
Keep the sidebar expanded

### ISSUE THREAD

**Issue by LoricAndre** [artsyfriedchicken/EdgyArc-fr#43]
Is there a way to always keep the sidebar expanded ?

**Comment by artsyfriedchicken** [comment]
The sidebar should remain expanded as default behaviour. Could you please elaborate on what issues you are having?

**Comment by LoricAndre** [comment]
Sorry, I'll elaborate :

I followed the instructions to set edgyarc up, and everything looks amazing.

However, the sidebar is collapsed by default (showing only icons of non-pinned tabs), and expands to full width only on hover. The animation is a little sluggish, and since the pinned tabs take space once expanded the tabs are not at the same place when the sidebar is collapsed and expanded, making it kinda hard to quickly switch tabs as I need to wait for the sidebar to expand, move my mouse, and click.

I might have done something wrong during the setup to get this behavior, but I couldn't find the option to revert to an always expanded sidebar.

**Comment by artsyfriedchicken** [comment]
Please make sure you have it set up right! Sidebar autohide is dependent on the [Userchrome Toggle ](https://addons.mozilla.org/en-US/firefox/addon/userchrome-toggle/) extension. Please make sure you have that installed, and please make sure you have either the latest release or the current codebase for edgyarc and try again. 

Make sure you do NOT have `af.edgyarc.sidebar-always-collapsed` set to true.

**Comment by LoricAndre** [comment]
I have the Userchrome toggle extension installed and enabled, but isn't this to completely hide the sidebar ? I'm only talking about not having it collapsed.
The about:config key was not defined, I set it manually to false. The behaviour I'm looking for would be something like a `af.edgyarc.sidebar-never-collapsed` I guess.

**Comment by artsyfriedchicken** [comment]
> I have the Userchrome toggle extension installed and enabled, but isn't this to completely hide the sidebar ? 
No, it is to enable/disable the autohide. If you keep having issues, I would have to suggest trying on a separate new profile since I cannot replicate this errant behaviour on any of my instances.

**Comment by LoricAndre** [comment]
All right I might be an idiot, but at least I hope this is useful to someone later : the solution was simply to toggle off the userchrome extension, and the sidebar does not collapse anymore.

Sorry about this, and thank you for this amazing theme.
