### ISSUE TITLE
Toggle Sidebar

### ISSUE THREAD

**Issue by diip3sh** [artsyfriedchicken/EdgyArc-fr#45]
Hello @artsyfriedchicken is there a way to add keybinding to toggle sidebar show and hide like in the arc browser I have search the default keybinding of sideberry didn't found any

**Comment by artsyfriedchicken** [comment]
This theme uses [Userchrome Toggle](https://addons.mozilla.org/en-US/firefox/addon/userchrome-toggle/) to toggle the sidebar autoshow/hide. You can set/modify the default keyboard shortcut in Add-ons Manager > settings icon > Manage Extension Shortcuts and scroll all the way down to Userchrome Toggle

![Screenshot 2024-06-03 at 2 33 04 PM](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/100123017/aeb92644-9691-4bc6-a878-772475000d47)
