### ISSUE TITLE
I can't reproduce the theme exactly like you have it on the pictures

### ISSUE THREAD

**Issue by drkhero** [artsyfriedchicken/EdgyArc-fr#6]
I'm unable to make the theme look exactly like in the pictures. Could you please make a video tutorial alongside another video where you show how the theme looks and how to make it work?

**Comment by drkhero** [comment]
<img width="1527" alt="Screenshot 2024-02-25 at 8 11 53 PM" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/155139404/1a6a77fd-209d-4efb-8faa-59e71f58e8bd">
I did all the steps you said to do in the README, and my theme looks absolutely nothing like yours. Please help

**Comment by drkhero** [comment]
<img width="1403" alt="Screenshot 2024-02-25 at 8 19 01 PM" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/155139404/7a80e940-9c54-476e-b8b3-8d2e8e476d33">
Nice, so I think i finally got some of the theme to work. Here's a screenshot of how it looks like. Please let me know if I'm missing anything. I noticed a small bug bottom left it's not showing the whole thing. Other than that let me know if I did everything correctly

**Comment by MarshallYTHD** [comment]
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/15093189/2d581ad6-330e-4887-b93b-a7f4100f3bc7)
Did you have an issue where Sideberry when collapsed looked a bit off like this?

**Comment by drkhero** [comment]
I found another bug - when you have about 20 tabs open and say you click on the 20th tab, or the first tab, it will be glitchy and sort of scroll for you. Difficult to explain over text, but basically switching back and forth between tabs is not smooth.

Also, when you collapse the sidebeery sidebar to only keep icons of tabs, hovering over them brings the whole sidebar again, instead of just letting you click the icons. The animation is also not smooth.

This theme is great, just a few bugs to be fixed, but a lot of potential overall.

**Comment by artsyfriedchicken** [comment]
> Did you have an issue where Sideberry when collapsed looked a bit off like this? ![image](https://private-user-images.githubusercontent.com/15093189/308171212-2d581ad6-330e-4887-b93b-a7f4100f3bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTc5NjMsIm5iZiI6MTcwOTc5NzY2MywicGF0aCI6Ii8xNTA5MzE4OS8zMDgxNzEyMTItMmQ1ODFhZDYtMzMwZS00ODg3LWI5M2ItYTdmNDEwMGYzYmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA3NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYWMwZWRlYTZmZTA4NTg2ZDFlM2QzZTlhNDhmYjhkMjZhMGFlYTY0ZGM0MDgzZmIyYWM0OTk3MTRiYTFjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rFnCajSvblyrICWVsKnNUO02Vk_rf3vKleDAPbgeQIE)
> 
> ~When enabling translucency it also looks like this: https://i.imgur.com/tbYjEgt.png~ nvm, it seems translucent is for MacOS only.

Unfortunately windows development will only get underway once i have a couple of people willing to beta test this out in windows, as i currently dont have access to a windows machine.

**Comment by artsyfriedchicken** [comment]
> I found another bug - when you have about 20 tabs open and say you click on the 20th tab, or the first tab, it will be glitchy and sort of scroll for you. Difficult to explain over text, but basically switching back and forth between tabs is not smooth.
> 
> Also, when you collapse the sidebeery sidebar to only keep icons of tabs, hovering over them brings the whole sidebar again, instead of just letting you click the icons. The animation is also not smooth.
> 
> This theme is great, just a few bugs to be fixed, but a lot of potential overall.

The newest build v1.0.0-beta.5 has a ton of the theme rewritten. Please let me know if it solves your issues. 

Also, the sidebar auto-expanding on hover is a feature, not a bug lol. Im open to adding a preference you can use to stop the auto expand though!

**Comment by drkhero** [comment]
> > I found another bug - when you have about 20 tabs open and say you click on the 20th tab, or the first tab, it will be glitchy and sort of scroll for you. Difficult to explain over text, but basically switching back and forth between tabs is not smooth.
> > Also, when you collapse the sidebeery sidebar to only keep icons of tabs, hovering over them brings the whole sidebar again, instead of just letting you click the icons. The animation is also not smooth.
> > This theme is great, just a few bugs to be fixed, but a lot of potential overall.
> 
> The newest build v1.0.0-beta.5 has a ton of the theme rewritten. Please let me know if it solves your issues.
> 
> Also, the sidebar auto-expanding on hover is a feature, not a bug lol. Im open to adding a preference you can use to stop the auto expand though!

Appreciate the response. I haven't noticed any improvements when it comes to smoothness when going back and forth between tabs (when you have many of them opened), however i'd like to make a few suggestions:

- Bring the URL on the sidebar like Arc
- Tweak the UI on the sidebar (specifically the tabs) to look more like macOS/Arc

**Comment by artsyfriedchicken** [comment]
> > > I found another bug - when you have about 20 tabs open and say you click on the 20th tab, or the first tab, it will be glitchy and sort of scroll for you. Difficult to explain over text, but basically switching back and forth between tabs is not smooth.
> > > Also, when you collapse the sidebeery sidebar to only keep icons of tabs, hovering over them brings the whole sidebar again, instead of just letting you click the icons. The animation is also not smooth.
> > > This theme is great, just a few bugs to be fixed, but a lot of potential overall.
> > 
> > 
> > The newest build v1.0.0-beta.5 has a ton of the theme rewritten. Please let me know if it solves your issues.
> > Also, the sidebar auto-expanding on hover is a feature, not a bug lol. Im open to adding a preference you can use to stop the auto expand though!
> 
> Appreciate the response. I haven't noticed any improvements when it comes to smoothness when going back and forth between tabs (when you have many of them opened), however i'd like to make a few suggestions:
> 
>     * Bring the URL on the sidebar like Arc
> 
>     * Tweak the UI on the sidebar (specifically the tabs) to look more like macOS/Arc

sorry, im not really interested in making this an arc clone. I'm just making something i would personally like to use. feel free to make the changes yourself though, thats the beauty of open source!!

**Comment by drkhero** [comment]
> > > > I found another bug - when you have about 20 tabs open and say you click on the 20th tab, or the first tab, it will be glitchy and sort of scroll for you. Difficult to explain over text, but basically switching back and forth between tabs is not smooth.
> > > > Also, when you collapse the sidebeery sidebar to only keep icons of tabs, hovering over them brings the whole sidebar again, instead of just letting you click the icons. The animation is also not smooth.
> > > > This theme is great, just a few bugs to be fixed, but a lot of potential overall.
> > > 
> > > 
> > > The newest build v1.0.0-beta.5 has a ton of the theme rewritten. Please let me know if it solves your issues.
> > > Also, the sidebar auto-expanding on hover is a feature, not a bug lol. Im open to adding a preference you can use to stop the auto expand though!
> > 
> > 
> > Appreciate the response. I haven't noticed any improvements when it comes to smoothness when going back and forth between tabs (when you have many of them opened), however i'd like to make a few suggestions:
> > ```
> > * Bring the URL on the sidebar like Arc
> > 
> > * Tweak the UI on the sidebar (specifically the tabs) to look more like macOS/Arc
> > ```
> 
> sorry, im not really interested in making this an arc clone. I'm just making something i would personally like to use. feel free to make the changes yourself though, thats the beauty of open source!!

Thanks for the idea, I'm extremely busy these days, but I'll see if I can find some time to make the tweaks myself. You did give me a very good baseline here.

**Comment by jo-adithya** [comment]
Hey @artsyfriedchicken, really great stuff you have here 😁 Thanks for sharing this all! 

I have a question on tweaking this a bit. Do you know how to increase the transparency of the toolbar and the sidebar? I tried changing the background color alpha but didn't quite make it. I have no idea how to change the alpha for the sidebar as well. Here is my current state:

<img width="1440" alt="Screenshot 2024-03-21 at 7 23 59 PM" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/65324195/7a369426-12d1-4eb5-b543-4123f5ecf9ed">

The sidebar color is the only one that is not transparent. Do you know how to fix this? Any help would be very much appreciated 😁 Thanks!

**Comment by artsyfriedchicken** [comment]
The sidebar unfortunately can NOT be transparent. lmao. 

This is essentially why the code for this is SO fucking annoying XD 
The sidebar is a separate process from the browser ui. and as such, has a white background behind it. that cannot be changed or removed. The way i simulate the transparency is changing the opacity for #sidebar-box and #sidebar.
