### ISSUE TITLE
tab drag and drop guideline is not in line

### ISSUE THREAD

**Issue by AkiVonAkira** [artsyfriedchicken/EdgyArc-fr#8]
I have read some of the other issues, so this may just be a Windows thing, but when dragging a tab the line shown is not in a correct position.
When dropping the tab around the center point of another tab it places it under it, but when dropping it under the tab it makes it a child tab, so I think this behavior is odd too.
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/113895247/17601905-a1ca-4af5-b637-be3764ae3587)

**Comment by artsyfriedchicken** [comment]
yup yup! noticed it myself! not entirely sure how to fix it though lmao

**Comment by AkiVonAkira** [comment]
I tried looking at the code myself, but I haven't the slightest clue on firefox css

**Comment by AkiVonAkira** [comment]
Updated but it's not fully fixed :( I assumed it might be on my end only as I remove some of the title prefaces so I can have the sidebar always collapsed until hover, because otherwise with the extension it switches back to non collapsed by itself and that was driving me mad :p But after a quick test that is not the case.

**Comment by artsyfriedchicken** [comment]
Yeah, the scrollbar introduces a LOT of jank, and sometimes just flat out refuses to go away. Ive had it turned off in sidebery settings simply because of that!

As for mucking around with the title prefaces - dont. lmao XD 
I'll add in an optional config entry that'll do it for you this week

**Comment by AkiVonAkira** [comment]
Alright, you the goat! lmao

**Comment by artsyfriedchicken** [comment]
Just a little update - next commit later today should add support for uc.tweak.af.auto-collapse-sidebar as a possible alternative method of auto collapsing the sidebar wihtout using userchrome toggle.
