### ISSUE TITLE
Problems with sidebar alignment, url bar icons and height of url bar area is reduced.

### ISSUE THREAD

**Issue by bfayers** [artsyfriedchicken/EdgyArc-fr#9]
**Describe the bug**
The sidebar is slightly misaligned when collapsed (icons pushed to the right with a gap) and when expanded it slighlty covers the bottom edge of the first few bookmarks. 

It can be solved by enabling `uc.tweak.af.translucent-arc` but I prefer to have the translucent features off.

I also have some extensions that use icons inside the URL bar, notably https://addons.mozilla.org/en-GB/firefox/addon/traduzir-paginas-web/. At some point a change was made and after clicking this and mousing into the popup causes it to disappear.

The url bar height overall is also considerably smaller on my system compared to the screenshots since updating to b6 over b5.

### Sidebar issues
<img width="162" alt="image" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/7032777/db117e22-6520-4154-89cf-4c7c79e8d727">
<img width="161" alt="image" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/7032777/d7178970-2f62-4f5b-97bf-2f92e1cab8e2">

### URL Bar Icons
![2024-03-12_19-49-07 (1)](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/7032777/5916ab57-46e3-4af7-b5ef-32980cf41eaa)

### URL Bar Area Height
<img width="304" alt="image" src="https://github.com/artsyfriedchicken/EdgyArc-fr/assets/7032777/73839a52-0531-4a76-8362-8110ae4aab27">

## Some Fixes
Found some fixes myself, will update this section as I find more.

### Sidebar issues

add
```
margin: 0px !important;
padding: 0px !important;
```
at https://github.com/artsyfriedchicken/EdgyArc-fr/blob/main/chrome/EdgyArc-fr/main.css#L142

to remove additonal gap on the left of browser content that isn't present using translucent-arc pref add
```
  & #appcontent .browserStack {
    overflow: hidden !important;
    margin-left: 0 !important;
  }
```
at https://github.com/artsyfriedchicken/EdgyArc-fr/blob/main/chrome/EdgyArc-fr/main.css#L191

### URL Bar Icons
Comment out/remove from https://github.com/artsyfriedchicken/EdgyArc-fr/blob/main/chrome/EdgyArc-fr/main.css#L310 to https://github.com/artsyfriedchicken/EdgyArc-fr/blob/main/chrome/EdgyArc-fr/main.css#L317 

(Incorrect(?) behaviour was introduced at https://github.com/artsyfriedchicken/EdgyArc-fr/commit/cf5b5b912eed9ca994807749cdd5d4e5da371206#diff-6bfc38efc55a1855d1a8280ea18bac7864d0be264da3ae8ae05e2a4cd06f9cf9R222)

### URL Bar Area Height
at https://github.com/artsyfriedchicken/EdgyArc-fr/blob/main/chrome/EdgyArc-fr/main.css#L187 swap to `--uc-tab-top-margin: 10px;` This doesn't move the (macOS) window buttons down with it though.

**Comment by artsyfriedchicken** [comment]
> The url bar height overall is also considerably smaller on my system compared to the screenshots since updating to b6 over b5.

Please make sure to turn on uc.tweak.floating-tabs !!

**Comment by artsyfriedchicken** [comment]
I'm afraid I cannot replicate your sidebar issues. :( 

 Please make sure you have the latest version of https://github.com/bmFtZQ/edge-frfox/ installed?

**Comment by bfayers** [comment]
🤦 I found that I had another stylesheet loaded I had forgotten about, as it wasn't causing any issues before. For what it's worth the style loaded was https://github.com/Bali10050/ModernDevtools
